create table images
(
    image_id   bigint generated by default as identity
        constraint images_pk
            primary key,
    image_path text not null,
    image_type text not null,
    status     text not null
);

alter table images
    owner to postgres;

create table keywords
(
    keyword_id bigint generated by default as identity
        constraint keywords_pk
            primary key,
    keyword    text not null
);

alter table keywords
    owner to postgres;

create table keywords_of_images
(
    image_id   bigint not null
        constraint keywords_of_images_images_image_id_fk
            references images,
    keyword_id bigint not null
        constraint keywords_of_images_keywords_keyword_id_fk
            references keywords
);

alter table keywords_of_images
    owner to postgres;

